displayName: "Daily $5 Budget Alert"
budgetFilter:
  projects:
    - "projects/1029464172302"
  creditTypesTreatment: INCLUDE_ALL_CREDITS
amount:
  specifiedAmount:
    currencyCode: "USD"
    units: "150"
thresholdRules:
  - thresholdPercent: 1.0
    spendBasis: CURRENT_SPEND
notificationsRule:
  pubsubTopic: "projects/gen-lang-client-0167192380/topics/budget-disable-trigger"
  monitoringNotificationChannels: []
  disableDefaultIamRecipients: false
